# /config/application.yml
defaults: &defaults
  apns4r_cert_file: <%= Rails.root.join("certs", "certkey.pem") %>
  apns4r_cert_key: <%= Rails.root.join("certs", "pkey.pem") %>
  apns4r_push_host: 'gateway.sandbox.push.apple.com'
  apns4r_push_port: 2195
  apns4r_feedback_host: 'feedback.sandbox.push.apple.com'
  apns4r_feedback_port: 2196

development:
  <<: *defaults
  profile: true

test:
  <<: *defaults

production:
  <<: *defaults
